name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What happened?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: expexted
    attributes:
      label: What did you expect to happen?
      description: What would happen if everything was going smoothly?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How can we reproduce this issue?
      description: as minimally and precisely as possible please
      placeholder: Give us a nice bullited list of things that lead up to this bug
    validations:
      required: true
  - type: textarea
    id: extra-details
    attributes:
      label: Is there anything else we need to know about?
      description: Tell us the rest of the story
    validations:
      required: false
  - type: input
    id: syna-version
    attributes:
      label: Syna theme version
      placeholder: ex. 0.17.4
    validations:
      required: false
  - type: input
    id: hugo-version
    attributes:
      label: Hugo version
      placeholder: ex. 0.101.0
    validations:
      required: false
  - type: textarea
    id: other-version
    attributes:
      label: Versions of other dependencies
      placeholder: ex. jumbo monkey forms - 1.0
    validations:
      required: false
